frase = 'Curso em Video Pthon'
frase2 = '   Aprenda Python   '
print(frase)
print(frase2)
print(frase[9])
print(frase[::3])
print(len(frase))
print(frase.count('o'))
print(frase.find('deo'))
print('Curso' in frase)
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase2.strip())
print(frase.split())
print('_'.join(frase))
