b = input('Digite augo:')
print(type(b))
print(b.isalnum())
print(b.isalpha())
print(b.isascii())
print(b.isdecimal())
print(b.isdigit())
print(b.isidentifier())
print(b.islower())
print(b.isnumeric())
print(b.isprintable())
print(b.isspace())
print(b.isalpha())
print(b.isupper())